name: neffos
description: A new Flutter package.
version: 0.0.1
author:
homepage: none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^1.1.0
  json_serializable: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.3

flutter:
  uses-material-design: true